### ISSUE TITLE
LOGO: Upload MT Umgebung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_tenants#10]
### Aktuelles Verhalten

Ein Logo wird nach dem Upload auf der Gruppe nur sehr klein angezeigt. Unabhängig von der Grösse des Logos. Beim Test wurden verschiedene Grössen ausprobiert. Das Original Logo ist 230x30 px gross. Auch mit dieser Grösse wird das Logo verkleinert.

### Gewünschtes Verhalten

Logo sollte nicht unnötig verkleinert werden.

### Schritte zu reproduzieren

1. Eine Gruppe bearbeiten
2. Neues Logo auswählen
3. Upload
4. Logo oben links wird nur sehr klein angezeigt.

### Wann ist der Fehler aufgetreten?

Aktuell nur in der MT Umgebung festgestellt. Bei der dsj Integrationsumgebung wird das Logo grösser dargestellt.

### hitobito version

Version 1.27.11

### Organisation

MT Umgebung

## ToDo

- [ ] Issue aufbereiten
- [ ] ggf. Sentry-Issues dazu heraussuchen
- [ ] Schritte für Fehlerbehebung erfassen
- [ ] Team informieren, um es einzuplanen

### Fehlerbehebung

- [x] Prüfen, ob Bild aktiv verkleinert oder nur falsch angezeigt wird
- [x] Bild nicht unnötig skalieren
- [x] Bild so gross wie möglich anzeigen

**Comment by daniel-illi** [comment]
Ich habe versucht, das bei mir lokal zu reproduzieren.
Allerdings kann ich kein Fehlverhalten feststellen. Auf dem logo sind diese styles hinterlegt:
```
.logo-image img {
    max-width: 230px;
    max-height: 30px;
}
```
Das sind auch exakt die Dimensionen des hitobito logo images welches standardmässig angezeigt wird. Selber hochgeladene Logos werden verkleinert dargestellt, falls sie diese Dimensionen überschreiten.

Dieses Verhalten habe ich auch auf https://puzzle.hitobito.com/ überprüft.
Aus meiner Sicht ist also alles in Ordnung.

**Comment by daniel-illi** [comment]
Ich habe das auch mit einem grossen Bild getestet (2000x2423).
Auf der Website wird das Originalbild eingebunden und Client seitig skaliert.

**Comment by mtnstar** [comment]
gut, dann schliessen wir doch dieses Ticket hier mal.
falls Problem wieder auftauchen sollte, dann reopen oder new issue.
